In [1]:
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

df = pd.read_csv('saglikdataset.csv')

print("Veri Seti İlk 5 Satır:")
print(df.head())

transactions = []

for index, row in df.iterrows():
    transaction = [row['Disease'].strip()] 

    for col in df.columns[1:]:
        item = row[col]
        if pd.notna(item):  
            transaction.append(item.strip())
            
    transactions.append(transaction)

print(f"\nToplam İşlem (Vaka) Sayısı: {len(transactions)}")
print("Örnek Bir İşlem (Hasta Kaydı):", transactions[0])

te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df_encoded = pd.DataFrame(te_ary, columns=te.columns_)

print("\nAlgoritmaya Girecek Veri Formatı:")
print(df_encoded.head())

Veri Seti İlk 5 Satır:
            Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches
3  Fungal infection     itching              skin_rash    dischromic _patches
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches       NaN       NaN       NaN       NaN       NaN
1                   NaN       NaN       NaN       NaN       NaN       NaN
2                   NaN       NaN       NaN       NaN       NaN       NaN
3                   NaN       NaN       NaN       NaN       NaN       NaN
4                   NaN       NaN       NaN       NaN       NaN       NaN

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0        NaN        NaN        NaN        NaN        NaN        NaN
1        NaN        NaN        NaN        NaN        NaN        NaN
2        NaN        NaN        NaN        NaN        NaN        NaN
3        NaN        NaN        NaN        NaN        NaN        NaN
4        NaN        NaN        NaN        NaN        NaN        NaN

  Symptom_16 Symptom_17
0        NaN        NaN
1        NaN        NaN
2        NaN        NaN
3        NaN        NaN
4        NaN        NaN

Toplam İşlem (Vaka) Sayısı: 4920
Örnek Bir İşlem (Hasta Kaydı): ['Fungal infection', 'itching', 'skin_rash', 'nodal_skin_eruptions', 'dischromic _patches']

Algoritmaya Girecek Veri Formatı:
   (vertigo) Paroymsal  Positional Vertigo   AIDS   Acne  Alcoholic hepatitis  \
0                                    False  False  False                False
1                                    False  False  False                False
2                                    False  False  False                False
3                                    False  False  False                False
4                                    False  False  False                False

   Allergy  Arthritis  Bronchial Asthma  Cervical spondylosis  Chicken pox  \
0    False      False             False                 False        False
1    False      False             False                 False        False
2    False      False             False                 False        False
3    False      False             False                 False        False
4    False      False             False                 False        False

   Chronic cholestasis  ...  vomiting  watering_from_eyes  weakness_in_limbs  \
0                False  ...     False               False              False
1                False  ...     False               False              False
2                False  ...     False               False              False
3                False  ...     False               False              False
4                False  ...     False               False              False

   weakness_of_one_body_side  weight_gain  weight_loss  yellow_crust_ooze  \
0                      False        False        False              False
1                      False        False        False              False
2                      False        False        False              False
3                      False        False        False              False
4                      False        False        False              False

   yellow_urine  yellowing_of_eyes  yellowish_skin
0         False              False           False
1         False              False           False
2         False              False           False
3         False              False           False
4         False              False           False

[5 rows x 172 columns]

In [7]:
df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
apriori(df_encoded, min_support=0.05)[1:16]

     support itemsets
1   0.069512     (53)
2   0.091463     (54)
3   0.141463     (58)
4   0.162195     (59)
5   0.114634     (66)
6   0.115854     (68)
7   0.114634     (71)
8   0.068293     (74)
9   0.093902     (77)
10  0.392683     (81)
11  0.230488     (84)
12  0.276829     (86)
13  0.096341     (94)
14  0.137805     (96)
15  0.139024     (97)

In [13]:
print("Kural Sayısı:", len(apriori(df_encoded, min_support=0.05)))

Kural Sayısı: 562

In [14]:
apriori(df_encoded, min_support=0.05, use_colnames=True)[1:16]

     support                        itemsets
1   0.069512  (blurred_and_distorted_vision)
2   0.091463                (breathlessness)
3   0.141463                    (chest_pain)
4   0.162195                        (chills)
5   0.114634                         (cough)
6   0.115854                    (dark_urine)
7   0.114634                     (diarrhoea)
8   0.068293                     (dizziness)
9   0.093902              (excessive_hunger)
10  0.392683                       (fatigue)
11  0.230488                      (headache)
12  0.276829                    (high_fever)
13  0.096341                  (irritability)
14  0.137805                       (itching)
15  0.139024                    (joint_pain)

In [15]:
frequent_itemsets = apriori(df_encoded, min_support=0.15, use_colnames=True)

rules1 = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.30)
print("Oluşan Kural Sayısı:", len(rules1))

Oluşan Kural Sayısı: 16

In [18]:
rules1 = rules1.sort_values(['confidence'], ascending=False)

rules1[1:11]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,antecedent_len,consequents_len
15,(nausea),(vomiting),0.232927,0.389024,0.198780,0.853403,2.193701,1.0,0.108166,4.167726,0.709384,0.469741,0.760061,0.682187,1,1
0,(abdominal_pain),(vomiting),0.209756,0.389024,0.176829,0.843023,2.167019,1.0,0.095229,3.892141,0.681481,0.419075,0.743072,0.648784,1,1
2,(yellowish_skin),(abdominal_pain),0.185366,0.209756,0.154878,0.835526,3.983323,1.0,0.115996,4.804683,0.919374,0.644670,0.791870,0.786949,1,1
3,(abdominal_pain),(yellowish_skin),0.209756,0.185366,0.154878,0.738372,3.983323,1.0,0.115996,3.113713,0.947750,0.644670,0.678840,0.786949,1,1
5,(high_fever),(fatigue),0.276829,0.392683,0.198780,0.718062,1.828604,1.0,0.090074,2.154078,0.626595,0.422280,0.535764,0.612136,1,1
12,(loss_of_appetite),(yellowing_of_eyes),0.234146,0.165854,0.159756,0.682292,4.113817,1.0,0.120922,2.625510,0.988331,0.664975,0.619122,0.822763,1,1
7,(loss_of_appetite),(fatigue),0.234146,0.392683,0.157317,0.671875,1.710986,1.0,0.065372,1.850871,0.542586,0.335065,0.459714,0.536248,1,1
10,(loss_of_appetite),(vomiting),0.234146,0.389024,0.156098,0.666667,1.713689,1.0,0.065009,1.832927,0.543790,0.334204,0.454424,0.533960,1,1
14,(vomiting),(nausea),0.389024,0.232927,0.198780,0.510972,2.193701,1.0,0.108166,1.568566,0.890624,0.469741,0.362475,0.682187,1,1
4,(fatigue),(high_fever),0.392683,0.276829,0.198780,0.506211,1.828604,1.0,0.090074,1.464534,0.746126,0.422280,0.317189,0.612136,1,1

In [19]:
rules1["antecedent_len"] = rules1["antecedents"].apply(lambda x: len(x))
rules1["consequents_len"] = rules1["consequents"].apply(lambda x: len(x))
rules1[1:6]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,antecedent_len,consequents_len
15,(nausea),(vomiting),0.232927,0.389024,0.198780,0.853403,2.193701,1.0,0.108166,4.167726,0.709384,0.469741,0.760061,0.682187,1,1
0,(abdominal_pain),(vomiting),0.209756,0.389024,0.176829,0.843023,2.167019,1.0,0.095229,3.892141,0.681481,0.419075,0.743072,0.648784,1,1
2,(yellowish_skin),(abdominal_pain),0.185366,0.209756,0.154878,0.835526,3.983323,1.0,0.115996,4.804683,0.919374,0.644670,0.791870,0.786949,1,1
3,(abdominal_pain),(yellowish_skin),0.209756,0.185366,0.154878,0.738372,3.983323,1.0,0.115996,3.113713,0.947750,0.644670,0.678840,0.786949,1,1
5,(high_fever),(fatigue),0.276829,0.392683,0.198780,0.718062,1.828604,1.0,0.090074,2.154078,0.626595,0.422280,0.535764,0.612136,1,1

In [20]:
rules2 = association_rules(frequent_itemsets, metric="lift", min_threshold=0.5)

rules2 = rules2.sort_values(['lift'], ascending=False)

rules2[1:6]
rules2["antecedent_len"] = rules2["antecedents"].apply(lambda x: len(x))

rules2["consequents_len"] = rules2["consequents"].apply(lambda x: len(x))

rules2[1:6]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,antecedent_len,consequents_len
13,(yellowing_of_eyes),(loss_of_appetite),0.165854,0.234146,0.159756,0.963235,4.113817,1.0,0.120922,20.831220,0.907415,0.664975,0.951995,0.822763,1,1
3,(abdominal_pain),(yellowish_skin),0.209756,0.185366,0.154878,0.738372,3.983323,1.0,0.115996,3.113713,0.947750,0.644670,0.678840,0.786949,1,1
2,(yellowish_skin),(abdominal_pain),0.185366,0.209756,0.154878,0.835526,3.983323,1.0,0.115996,4.804683,0.919374,0.644670,0.791870,0.786949,1,1
14,(vomiting),(nausea),0.389024,0.232927,0.198780,0.510972,2.193701,1.0,0.108166,1.568566,0.890624,0.469741,0.362475,0.682187,1,1
15,(nausea),(vomiting),0.232927,0.389024,0.198780,0.853403,2.193701,1.0,0.108166,4.167726,0.709384,0.469741,0.760061,0.682187,1,1

In [23]:
rules1[(rules1['antecedent_len'] >= 1) &
       (rules1['confidence'] >= 0.20) &
       (rules1['lift'] > 1) ].sort_values(['confidence'], ascending=False)[1:10]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,antecedent_len,consequents_len
15,(nausea),(vomiting),0.232927,0.389024,0.198780,0.853403,2.193701,1.0,0.108166,4.167726,0.709384,0.469741,0.760061,0.682187,1,1
0,(abdominal_pain),(vomiting),0.209756,0.389024,0.176829,0.843023,2.167019,1.0,0.095229,3.892141,0.681481,0.419075,0.743072,0.648784,1,1
2,(yellowish_skin),(abdominal_pain),0.185366,0.209756,0.154878,0.835526,3.983323,1.0,0.115996,4.804683,0.919374,0.644670,0.791870,0.786949,1,1
3,(abdominal_pain),(yellowish_skin),0.209756,0.185366,0.154878,0.738372,3.983323,1.0,0.115996,3.113713,0.947750,0.644670,0.678840,0.786949,1,1
5,(high_fever),(fatigue),0.276829,0.392683,0.198780,0.718062,1.828604,1.0,0.090074,2.154078,0.626595,0.422280,0.535764,0.612136,1,1
12,(loss_of_appetite),(yellowing_of_eyes),0.234146,0.165854,0.159756,0.682292,4.113817,1.0,0.120922,2.625510,0.988331,0.664975,0.619122,0.822763,1,1
7,(loss_of_appetite),(fatigue),0.234146,0.392683,0.157317,0.671875,1.710986,1.0,0.065372,1.850871,0.542586,0.335065,0.459714,0.536248,1,1
10,(loss_of_appetite),(vomiting),0.234146,0.389024,0.156098,0.666667,1.713689,1.0,0.065009,1.832927,0.543790,0.334204,0.454424,0.533960,1,1
14,(vomiting),(nausea),0.389024,0.232927,0.198780,0.510972,2.193701,1.0,0.108166,1.568566,0.890624,0.469741,0.362475,0.682187,1,1